#!/usr/bin/env python3
"""Create Wingman's per-install local token without printing the secret."""

from __future__ import annotations

import argparse
import json
import os
import secrets
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ENV = REPO_ROOT / ".env"
DEFAULT_EXTENSION_CONFIG = REPO_ROOT / "extension" / "local-config.js"
TOKEN_KEY = "WINGMAN_TOKEN"


def _read_lines(path: Path) -> list[str]:
    if path.exists():
        return path.read_text(encoding="utf-8").splitlines()
    return [
        "# Wingman local configuration. Never commit this file.",
        "WORKIVA_CLIENT_ID=",
        "WORKIVA_CLIENT_SECRET=",
        "",
        "# Generated by scripts/configure_local.py.",
        f"{TOKEN_KEY}=",
    ]


def _current_value(lines: list[str], key: str) -> str:
    prefix = f"{key}="
    for line in lines:
        if line.startswith(prefix):
            return line[len(prefix) :].strip()
    return ""


def _set_value(lines: list[str], key: str, value: str) -> list[str]:
    prefix = f"{key}="
    result: list[str] = []
    replaced = False
    for line in lines:
        if line.startswith(prefix):
            if not replaced:
                result.append(prefix + value)
                replaced = True
            continue
        result.append(line)
    if not replaced:
        if result and result[-1]:
            result.append("")
        result.extend(["# Generated by scripts/configure_local.py.", prefix + value])
    return result


def configure(env_path: Path, extension_config_path: Path) -> str:
    lines = _read_lines(env_path)
    token = _current_value(lines, TOKEN_KEY)
    status = "preserved"
    if not token:
        token = secrets.token_urlsafe(32)
        lines = _set_value(lines, TOKEN_KEY, token)
        status = "generated"

    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    os.chmod(env_path, 0o600)

    payload = json.dumps({"token": token}, separators=(",", ":"))
    extension_config_path.parent.mkdir(parents=True, exist_ok=True)
    extension_config_path.write_text(
        "// Generated locally by scripts/configure_local.py; gitignored.\n"
        f"globalThis.WINGMAN_LOCAL_CONFIG = Object.freeze({payload});\n",
        encoding="utf-8",
    )
    os.chmod(extension_config_path, 0o600)
    return status


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--env", type=Path, default=DEFAULT_ENV)
    parser.add_argument(
        "--extension-config", type=Path, default=DEFAULT_EXTENSION_CONFIG
    )
    args = parser.parse_args()
    status = configure(args.env, args.extension_config)
    print(f"Wingman local token {status}; extension config synchronized (secret not printed).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
